In [1]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [3]:
data = pd.read_csv('iris_classification/final_data.csv')

In [4]:
data.head()

Unnamed: 0  Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0           0   0            5.1           3.5            1.4           0.2   
1           1   1            4.7           3.2            1.6           0.2   
2           2   2            4.9           3.1            1.5           0.1   
3           3   3            4.4           2.9            1.4           0.2   
4           4   4            5.0           3.4            1.5           0.2   

       Species  
0  Iris-setosa  
1  Iris-setosa  
2  Iris-setosa  
3  Iris-setosa  
4  Iris-setosa

In [9]:
data.drop(['Unnamed: 0', 'Id'], axis=1, inplace=True)

In [10]:
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.7           3.2            1.6           0.2  Iris-setosa
2            4.9           3.1            1.5           0.1  Iris-setosa
3            4.4           2.9            1.4           0.2  Iris-setosa
4            5.0           3.4            1.5           0.2  Iris-setosa

## Label Encoding

In [11]:
le = LabelEncoder()

In [14]:
data['Species'] = le.fit_transform(data['Species'])

In [15]:
data.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0            5.1           3.5            1.4           0.2        0
1            4.7           3.2            1.6           0.2        0
2            4.9           3.1            1.5           0.1        0
3            4.4           2.9            1.4           0.2        0
4            5.0           3.4            1.5           0.2        0

### Data Controls

In [16]:
data.isna().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [18]:
data.dtypes

SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species            int32
dtype: object

## Train_test_split

In [19]:
from sklearn.model_selection import train_test_split

In [40]:
X_train, X_test, Y_train, Y_test = train_test_split(data.iloc[:, :-1], data.iloc[:, -1], test_size=0.2)

In [41]:
X_train

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
22             5.1           3.5       1.400000           0.3
117            6.2           2.8       4.800000           1.8
84             6.3           3.3       3.707229           1.6
65             6.1           2.8       4.700000           1.2
11             4.8           3.4       1.600000           0.2
..             ...           ...            ...           ...
99             6.1           2.9       3.707229           1.4
20             5.1           3.8       1.500000           0.3
71             6.6           2.9       4.600000           1.3
132            6.7           3.1       5.600000           2.4
138            6.3           2.7       4.900000           1.8

[123 rows x 4 columns]

In [42]:
Y_train

22     0
117    2
84     1
65     1
11     0
      ..
99     1
20     0
71     1
132    2
138    2
Name: Species, Length: 123, dtype: int32

In [43]:
Y_train.value_counts()

2    44
1    42
0    37
Name: Species, dtype: int64

In [44]:
Y_test.value_counts()

1    11
0    10
2    10
Name: Species, dtype: int64

## Creating Model

In [45]:
import xgboost as xgb

In [48]:
xgb_cls = xgb.XGBClassifier(objective="multiclass:softmax", num_class=3)

In [49]:
xgb_cls.fit(X_train, Y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_bin=256, max_cat_threshold=64, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_class=3, num_parallel_tree=1,
              objective='multi:softprob', ...)

In [51]:
X_test

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
47             5.7           2.8            4.5      1.300000
5              4.6           3.4            1.4      0.300000
144            5.8           2.8            5.1      1.180357
72             7.0           3.2            4.7      1.400000
114            6.4           2.8            5.6      2.100000
86             5.7           2.9            4.2      1.300000
150            6.8           3.0            5.5      2.100000
28             5.2           4.1            1.5      0.100000
19             5.1           3.7            1.5      0.400000
37             4.4           3.2            1.3      0.200000
31             4.9           3.1            1.5      0.100000
80             5.8           2.6            4.0      1.200000
43             5.1           3.8            1.6      0.200000
40             5.0           3.5            1.3      0.300000
110            6.4           2.8            5.6      2.200000
102            6.1           2.6            5.6      1.400000
56             5.8           2.7            4.1      1.000000
140            6.2           3.4            5.4      2.300000
70             5.6           2.5            3.9      1.100000
69             5.9           3.2            4.8      1.800000
78             6.7           3.1            4.7      1.500000
52             4.9           2.4            3.3      1.000000
64             6.4           2.9            4.3      1.300000
141            5.9           3.0            5.1      1.800000
15             5.0           3.4            1.6      0.400000
128            6.7           3.3            5.7      2.100000
79             6.0           3.4            4.5      1.600000
145            6.7           3.0            5.2      2.300000
9              4.7           3.2            1.3      0.200000
38             5.1           3.8            1.9      0.400000
135            6.8           3.2            5.9      2.300000

In [52]:
preds = xgb_cls.predict(X_test)

In [53]:
preds

array([1, 0, 2, 1, 2, 1, 2, 0, 0, 0, 0, 1, 0, 0, 2, 2, 1, 2, 1, 2, 1, 1,
       1, 2, 0, 2, 1, 2, 0, 0, 2], dtype=int64)

In [54]:
import numpy as np

In [55]:
np.array(Y_test)

array([1, 0, 2, 1, 2, 1, 2, 0, 0, 0, 0, 1, 0, 0, 2, 2, 1, 2, 1, 1, 1, 1,
       1, 2, 0, 2, 1, 2, 0, 0, 2])

In [56]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [57]:
accuracy_score(Y_test, preds)

0.967741935483871

In [58]:
confusion_matrix(Y_test, preds)

array([[10,  0,  0],
       [ 0, 10,  1],
       [ 0,  0, 10]], dtype=int64)