# Data Analysis

In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [51]:
datas = pd.read_csv('datas.txt')

In [52]:
datas

ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k

In [53]:
datas[['boy', 'kilo']]

boy  kilo
0   130    30
1   125    36
2   135    34
3   133    30
4   129    38
5   180    90
6   190    80
7   175    90
8   177    60
9   185   105
10  165    55
11  155    50
12  160    58
13  162    59
14  167    62
15  174    70
16  193    90
17  187    80
18  183    88
19  159    40
20  164    66
21  166    56

In [54]:
missing_datas = pd.read_csv('missingDatas.txt')

In [55]:
missing_datas

ulke  boy  kilo   yas cinsiyet
0    tr  130    30  10.0        e
1    tr  125    36  11.0        e
2    tr  135    34  10.0        k
3    tr  133    30   9.0        k
4    tr  129    38  12.0        e
5    tr  180    90  30.0        e
6    tr  190    80  25.0        e
7    tr  175    90  35.0        e
8    tr  177    60  22.0        k
9    us  185   105  33.0        e
10   us  165    55  27.0        k
11   us  155    50  44.0        k
12   us  160    58   NaN        k
13   us  162    59  41.0        k
14   us  167    62  55.0        k
15   fr  174    70  47.0        e
16   fr  193    90   NaN        e
17   fr  187    80  27.0        e
18   fr  183    88  28.0        e
19   fr  159    40  29.0        k
20   fr  164    66  32.0        k
21   fr  166    56  42.0        k

In [56]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [57]:
Yas = datas.iloc[:, 1:4].values
Yas

array([[130,  30,  10],
       [125,  36,  11],
       [135,  34,  10],
       [133,  30,   9],
       [129,  38,  12],
       [180,  90,  30],
       [190,  80,  25],
       [175,  90,  35],
       [177,  60,  22],
       [185, 105,  33],
       [165,  55,  27],
       [155,  50,  44],
       [160,  58,  39],
       [162,  59,  41],
       [167,  62,  55],
       [174,  70,  47],
       [193,  90,  23],
       [187,  80,  27],
       [183,  88,  28],
       [159,  40,  29],
       [164,  66,  32],
       [166,  56,  42]], dtype=int64)

In [58]:
imputer = imputer.fit(Yas[:, 1:4])

In [59]:
Yas[:, 1:4] = imputer.transform(Yas[:, 1:4])
Yas

array([[130,  30,  10],
       [125,  36,  11],
       [135,  34,  10],
       [133,  30,   9],
       [129,  38,  12],
       [180,  90,  30],
       [190,  80,  25],
       [175,  90,  35],
       [177,  60,  22],
       [185, 105,  33],
       [165,  55,  27],
       [155,  50,  44],
       [160,  58,  39],
       [162,  59,  41],
       [167,  62,  55],
       [174,  70,  47],
       [193,  90,  23],
       [187,  80,  27],
       [183,  88,  28],
       [159,  40,  29],
       [164,  66,  32],
       [166,  56,  42]], dtype=int64)

In [60]:
ulke = datas.iloc[:,0:1].values
ulke

array([['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr']], dtype=object)

In [61]:
le = preprocessing.LabelEncoder()

In [62]:
ulke[:,0] = le.fit_transform(datas.iloc[:,0])
ulke

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=object)

In [63]:
ohe = preprocessing.OneHotEncoder()

In [64]:
ulke = ohe.fit_transform(ulke).toarray()
ulke

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [65]:
sex = datas.iloc[:,-1:].values
sex

array([['e'],
       ['e'],
       ['k'],
       ['k'],
       ['e'],
       ['e'],
       ['e'],
       ['e'],
       ['k'],
       ['e'],
       ['k'],
       ['k'],
       ['k'],
       ['k'],
       ['k'],
       ['e'],
       ['e'],
       ['e'],
       ['e'],
       ['k'],
       ['k'],
       ['k']], dtype=object)

In [66]:
sex[:,-1] = le.fit_transform(datas.iloc[:,-1])
sex

array([[0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1]], dtype=object)

In [67]:
sex = ohe.fit_transform(sex).toarray()
sex

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [68]:
res1 = pd.DataFrame(data=ulke, index = range(22), columns = ['fr', 'tr', 'us'])
res1

fr   tr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0

In [69]:
res2 = pd.DataFrame(data=Yas, index = range(22), columns = ['boy', 'kilo', 'yas'])
res2

boy  kilo  yas
0   130    30   10
1   125    36   11
2   135    34   10
3   133    30    9
4   129    38   12
5   180    90   30
6   190    80   25
7   175    90   35
8   177    60   22
9   185   105   33
10  165    55   27
11  155    50   44
12  160    58   39
13  162    59   41
14  167    62   55
15  174    70   47
16  193    90   23
17  187    80   27
18  183    88   28
19  159    40   29
20  164    66   32
21  166    56   42

In [70]:
cinsiyet = datas.iloc[:,-1].values
cinsiyet

array(['e', 'e', 'k', 'k', 'e', 'e', 'e', 'e', 'k', 'e', 'k', 'k', 'k',
       'k', 'k', 'e', 'e', 'e', 'e', 'k', 'k', 'k'], dtype=object)

In [71]:
res3 = pd.DataFrame(data=sex[:,:1], index = range(22), columns = ['cinsiyet'])
res3

cinsiyet
0        1.0
1        1.0
2        0.0
3        0.0
4        1.0
5        1.0
6        1.0
7        1.0
8        0.0
9        1.0
10       0.0
11       0.0
12       0.0
13       0.0
14       0.0
15       1.0
16       1.0
17       1.0
18       1.0
19       0.0
20       0.0
21       0.0

In [72]:
r1 = pd.concat([res1, res2], axis=1)
r1

fr   tr   us  boy  kilo  yas
0   0.0  1.0  0.0  130    30   10
1   0.0  1.0  0.0  125    36   11
2   0.0  1.0  0.0  135    34   10
3   0.0  1.0  0.0  133    30    9
4   0.0  1.0  0.0  129    38   12
5   0.0  1.0  0.0  180    90   30
6   0.0  1.0  0.0  190    80   25
7   0.0  1.0  0.0  175    90   35
8   0.0  1.0  0.0  177    60   22
9   0.0  0.0  1.0  185   105   33
10  0.0  0.0  1.0  165    55   27
11  0.0  0.0  1.0  155    50   44
12  0.0  0.0  1.0  160    58   39
13  0.0  0.0  1.0  162    59   41
14  0.0  0.0  1.0  167    62   55
15  1.0  0.0  0.0  174    70   47
16  1.0  0.0  0.0  193    90   23
17  1.0  0.0  0.0  187    80   27
18  1.0  0.0  0.0  183    88   28
19  1.0  0.0  0.0  159    40   29
20  1.0  0.0  0.0  164    66   32
21  1.0  0.0  0.0  166    56   42

In [73]:
r2 = pd.concat([r1, res3], axis=1)
r2

fr   tr   us  boy  kilo  yas  cinsiyet
0   0.0  1.0  0.0  130    30   10       1.0
1   0.0  1.0  0.0  125    36   11       1.0
2   0.0  1.0  0.0  135    34   10       0.0
3   0.0  1.0  0.0  133    30    9       0.0
4   0.0  1.0  0.0  129    38   12       1.0
5   0.0  1.0  0.0  180    90   30       1.0
6   0.0  1.0  0.0  190    80   25       1.0
7   0.0  1.0  0.0  175    90   35       1.0
8   0.0  1.0  0.0  177    60   22       0.0
9   0.0  0.0  1.0  185   105   33       1.0
10  0.0  0.0  1.0  165    55   27       0.0
11  0.0  0.0  1.0  155    50   44       0.0
12  0.0  0.0  1.0  160    58   39       0.0
13  0.0  0.0  1.0  162    59   41       0.0
14  0.0  0.0  1.0  167    62   55       0.0
15  1.0  0.0  0.0  174    70   47       1.0
16  1.0  0.0  0.0  193    90   23       1.0
17  1.0  0.0  0.0  187    80   27       1.0
18  1.0  0.0  0.0  183    88   28       1.0
19  1.0  0.0  0.0  159    40   29       0.0
20  1.0  0.0  0.0  164    66   32       0.0
21  1.0  0.0  0.0  166    56   42       0.0

In [74]:
x_train, x_test, y_train, y_test = train_test_split(r1, res3, test_size=0.33, random_state=0)
x_train, x_test, y_train, y_test

(     fr   tr   us  boy  kilo  yas
 8   0.0  1.0  0.0  177    60   22
 6   0.0  1.0  0.0  190    80   25
 16  1.0  0.0  0.0  193    90   23
 4   0.0  1.0  0.0  129    38   12
 2   0.0  1.0  0.0  135    34   10
 5   0.0  1.0  0.0  180    90   30
 17  1.0  0.0  0.0  187    80   27
 9   0.0  0.0  1.0  185   105   33
 7   0.0  1.0  0.0  175    90   35
 18  1.0  0.0  0.0  183    88   28
 3   0.0  1.0  0.0  133    30    9
 0   0.0  1.0  0.0  130    30   10
 15  1.0  0.0  0.0  174    70   47
 12  0.0  0.0  1.0  160    58   39,
      fr   tr   us  boy  kilo  yas
 20  1.0  0.0  0.0  164    66   32
 10  0.0  0.0  1.0  165    55   27
 14  0.0  0.0  1.0  167    62   55
 13  0.0  0.0  1.0  162    59   41
 1   0.0  1.0  0.0  125    36   11
 21  1.0  0.0  0.0  166    56   42
 11  0.0  0.0  1.0  155    50   44
 19  1.0  0.0  0.0  159    40   29,
     cinsiyet
 8        0.0
 6        1.0
 16       1.0
 4        1.0
 2        0.0
 5        1.0
 17       1.0
 9        1.0
 7        1.0
 18       1.0
 3  

In [75]:
sc = StandardScaler()

In [76]:
X_train = sc.fit_transform(x_train)
X_train

array([[-0.63245553,  0.8660254 , -0.40824829,  0.45049444, -0.29657884,
        -0.26680787],
       [-0.63245553,  0.8660254 , -0.40824829,  1.00824945,  0.5096549 ,
         0.        ],
       [ 1.58113883, -1.15470054, -0.40824829,  1.13696215,  0.91277178,
        -0.17787191],
       [-0.63245553,  0.8660254 , -0.40824829, -1.6089087 , -1.18343596,
        -1.15616745],
       [-0.63245553,  0.8660254 , -0.40824829, -1.35148331, -1.34468271,
        -1.33403936],
       [-0.63245553,  0.8660254 , -0.40824829,  0.57920713,  0.91277178,
         0.44467979],
       [ 1.58113883, -1.15470054, -0.40824829,  0.87953676,  0.5096549 ,
         0.17787191],
       [-0.63245553, -1.15470054,  2.44948974,  0.79372829,  1.51744708,
         0.71148766],
       [-0.63245553,  0.8660254 , -0.40824829,  0.36468597,  0.91277178,
         0.88935957],
       [ 1.58113883, -1.15470054, -0.40824829,  0.70791983,  0.8321484 ,
         0.26680787],
       [-0.63245553,  0.8660254 , -0.40824829, -1.

In [77]:
X_test = sc.fit_transform(x_test)
X_test

array([[ 1.29099445, -0.37796447, -1.        ,  0.47240026,  1.32853794,
        -0.24991255],
       [-0.77459667, -0.37796447,  1.        ,  0.54952683,  0.20439045,
        -0.64977262],
       [-0.77459667, -0.37796447,  1.        ,  0.70377998,  0.91975703,
         1.58944379],
       [-0.77459667, -0.37796447,  1.        ,  0.31814711,  0.61317136,
         0.46983559],
       [-0.77459667,  2.64575131, -1.        , -2.53553608, -1.73731884,
        -1.92932485],
       [ 1.29099445, -0.37796447, -1.        ,  0.6266534 ,  0.30658568,
         0.5498076 ],
       [-0.77459667, -0.37796447,  1.        , -0.2217389 , -0.30658568,
         0.70975163],
       [ 1.29099445, -0.37796447, -1.        ,  0.08676739, -1.32853794,
        -0.48982859]])

# Multi Linear Regression

In [78]:
from sklearn.linear_model import LinearRegression

In [79]:
regressor = LinearRegression()

In [80]:
regressor.fit(x_train, y_train)

LinearRegression()

In [81]:
y_pred = regressor.predict(x_test)
y_pred

array([[ 0.98720204],
       [-0.12036863],
       [ 0.05009703],
       [ 0.07137418],
       [ 0.72473935],
       [ 0.64615044],
       [-0.03567453],
       [ 0.32612171]])

In [82]:
y_test

cinsiyet
20       0.0
10       0.0
14       0.0
13       0.0
1        1.0
21       0.0
11       0.0
19       0.0

In [83]:
boy = r2.iloc[:,3:4].values
boy

array([[130],
       [125],
       [135],
       [133],
       [129],
       [180],
       [190],
       [175],
       [177],
       [185],
       [165],
       [155],
       [160],
       [162],
       [167],
       [174],
       [193],
       [187],
       [183],
       [159],
       [164],
       [166]], dtype=int64)

In [84]:
left = r2.iloc[:,:3]

In [85]:
right = r2.iloc[:,4:]

In [86]:
data = pd.concat([left,right], axis=1)

In [87]:
x_train, x_test, y_train, y_test = train_test_split(data, boy, test_size=0.33, random_state=0)

In [88]:
regressor2 = LinearRegression()

In [89]:
regressor2.fit(x_train, y_train)

LinearRegression()

In [90]:
y_pred = regressor2.predict(x_test)
y_pred

array([[182.26638686],
       [152.87161474],
       [162.79386375],
       [158.30668577],
       [130.82888952],
       [173.96138408],
       [150.12782663],
       [157.26898922]])

In [91]:
x_test

fr   tr   us  kilo  yas  cinsiyet
20  1.0  0.0  0.0    66   32       0.0
10  0.0  0.0  1.0    55   27       0.0
14  0.0  0.0  1.0    62   55       0.0
13  0.0  0.0  1.0    59   41       0.0
1   0.0  1.0  0.0    36   11       1.0
21  1.0  0.0  0.0    56   42       0.0
11  0.0  0.0  1.0    50   44       0.0
19  1.0  0.0  0.0    40   29       0.0

In [92]:
y_test

array([[164],
       [165],
       [167],
       [162],
       [125],
       [166],
       [155],
       [159]], dtype=int64)

# Backward Elimination

In [93]:
import statsmodels.api as sm

In [94]:
X = np.append(arr = np.ones((22,1)).astype(int), values=data, axis=1)
X

array([[  1.,   0.,   1.,   0.,  30.,  10.,   1.],
       [  1.,   0.,   1.,   0.,  36.,  11.,   1.],
       [  1.,   0.,   1.,   0.,  34.,  10.,   0.],
       [  1.,   0.,   1.,   0.,  30.,   9.,   0.],
       [  1.,   0.,   1.,   0.,  38.,  12.,   1.],
       [  1.,   0.,   1.,   0.,  90.,  30.,   1.],
       [  1.,   0.,   1.,   0.,  80.,  25.,   1.],
       [  1.,   0.,   1.,   0.,  90.,  35.,   1.],
       [  1.,   0.,   1.,   0.,  60.,  22.,   0.],
       [  1.,   0.,   0.,   1., 105.,  33.,   1.],
       [  1.,   0.,   0.,   1.,  55.,  27.,   0.],
       [  1.,   0.,   0.,   1.,  50.,  44.,   0.],
       [  1.,   0.,   0.,   1.,  58.,  39.,   0.],
       [  1.,   0.,   0.,   1.,  59.,  41.,   0.],
       [  1.,   0.,   0.,   1.,  62.,  55.,   0.],
       [  1.,   1.,   0.,   0.,  70.,  47.,   1.],
       [  1.,   1.,   0.,   0.,  90.,  23.,   1.],
       [  1.,   1.,   0.,   0.,  80.,  27.,   1.],
       [  1.,   1.,   0.,   0.,  88.,  28.,   1.],
       [  1.,   1.,   0.,   0.,

In [95]:
X_l = data.iloc[:,[0,1,2,3,4,5]].values

In [96]:
X_l = np.array(X_l, dtype=float)

In [97]:
model = sm.OLS(boy, X_l).fit()

In [98]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.885
Model:                            OLS   Adj. R-squared:                  0.849
Method:                 Least Squares   F-statistic:                     24.69
Date:                Tue, 06 Dec 2022   Prob (F-statistic):           5.41e-07
Time:                        22:52:26   Log-Likelihood:                -73.950
No. Observations:                  22   AIC:                             159.9
Df Residuals:                      16   BIC:                             166.4
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           114.0688      8.145     14.005      0.000      96.802     131.335
x2           108.3030      5.736     18.880      0.000      96.143     120.463
x3           104.4714      9.195     11.361      0.000      84.978     123.964
x4             0.9211      0.119      7.737      0.000       0.669       1.174
x5             0.0814      0.221      0.369      0.717      -0.386       0.549
x6           -10.5980      5.052     -2.098      0.052     -21.308       0.112
==============================================================================
Omnibus:                        1.031   Durbin-Watson:                   2.759
Prob(Omnibus):                  0.597   Jarque-Bera (JB):                0.624
Skew:                           0.407   Prob(JB):                        0.732
Kurtosis:                       2.863   Cond. No.                         524.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [99]:
X_l = data.iloc[:,[0,1,2,3,5]].values

In [100]:
X_l = np.array(X_l, dtype=float)

In [101]:
model = sm.OLS(boy, X_l).fit()

In [102]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.884
Model:                            OLS   Adj. R-squared:                  0.857
Method:                 Least Squares   F-statistic:                     32.47
Date:                Tue, 06 Dec 2022   Prob (F-statistic):           9.32e-08
Time:                        22:52:26   Log-Likelihood:                -74.043
No. Observations:                  22   AIC:                             158.1
Df Residuals:                      17   BIC:                             163.5
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           115.6583      6.734     17.175      0.000     101.451     129.866
x2           109.0786      5.200     20.978      0.000      98.108     120.049
x3           106.5445      7.090     15.026      0.000      91.585     121.504
x4             0.9405      0.104      9.029      0.000       0.721       1.160
x5           -11.1093      4.733     -2.347      0.031     -21.096      -1.123
==============================================================================
Omnibus:                        0.871   Durbin-Watson:                   2.719
Prob(Omnibus):                  0.647   Jarque-Bera (JB):                0.459
Skew:                           0.351   Prob(JB):                        0.795
Kurtosis:                       2.910   Cond. No.                         397.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [103]:
X_l = data.iloc[:,[0,1,2,3]].values

In [104]:
X_l = np.array(X_l, dtype=float)

In [105]:
model = sm.OLS(boy, X_l).fit()

In [106]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.847
Model:                            OLS   Adj. R-squared:                  0.821
Method:                 Least Squares   F-statistic:                     33.16
Date:                Tue, 06 Dec 2022   Prob (F-statistic):           1.52e-07
Time:                        22:52:26   Log-Likelihood:                -77.131
No. Observations:                  22   AIC:                             162.3
Df Residuals:                      18   BIC:                             166.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           119.8136      7.265     16.491      0.000     104.550     135.077
x2           109.8084      5.804     18.919      0.000      97.615     122.002
x3           114.4212      6.984     16.382      0.000      99.747     129.095
x4             0.7904      0.092      8.595      0.000       0.597       0.984
==============================================================================
Omnibus:                        2.925   Durbin-Watson:                   2.855
Prob(Omnibus):                  0.232   Jarque-Bera (JB):                1.499
Skew:                           0.605   Prob(JB):                        0.473
Kurtosis:                       3.416   Cond. No.                         369.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""