In [135]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [136]:
datas = pd.read_csv('homework-tennis.txt')

In [137]:
datas.head()

outlook  temperature  humidity  windy play
0     sunny           85        85  False   no
1     sunny           80        90   True   no
2  overcast           83        86  False  yes
3     rainy           70        96  False  yes
4     rainy           68        80  False  yes

In [138]:
from sklearn import preprocessing

In [139]:
datas2 = datas.apply(preprocessing.LabelEncoder().fit_transform)

In [140]:
r = datas2.iloc[:,:1]

In [141]:
ohe = preprocessing.OneHotEncoder()

In [142]:
r = ohe.fit_transform(r).toarray()
r

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [143]:
weather = pd.DataFrame(data=r, index=range(14), columns=['o', 'r', 's'])

In [144]:
lastDatas = pd.concat([weather, datas.iloc[:,1:3]], axis=1)
lastDatas

o    r    s  temperature  humidity
0   0.0  0.0  1.0           85        85
1   0.0  0.0  1.0           80        90
2   1.0  0.0  0.0           83        86
3   0.0  1.0  0.0           70        96
4   0.0  1.0  0.0           68        80
5   0.0  1.0  0.0           65        70
6   1.0  0.0  0.0           64        65
7   0.0  0.0  1.0           72        95
8   0.0  0.0  1.0           69        70
9   0.0  1.0  0.0           75        80
10  0.0  0.0  1.0           75        70
11  1.0  0.0  0.0           72        90
12  1.0  0.0  0.0           81        75
13  0.0  1.0  0.0           71        91

In [145]:
lastDatas = pd.concat([datas2.iloc[:,-2:],lastDatas],axis=1)
lastDatas

windy  play    o    r    s  temperature  humidity
0       0     0  0.0  0.0  1.0           85        85
1       1     0  0.0  0.0  1.0           80        90
2       0     1  1.0  0.0  0.0           83        86
3       0     1  0.0  1.0  0.0           70        96
4       0     1  0.0  1.0  0.0           68        80
5       1     0  0.0  1.0  0.0           65        70
6       1     1  1.0  0.0  0.0           64        65
7       0     0  0.0  0.0  1.0           72        95
8       0     1  0.0  0.0  1.0           69        70
9       0     1  0.0  1.0  0.0           75        80
10      1     1  0.0  0.0  1.0           75        70
11      1     1  1.0  0.0  0.0           72        90
12      0     1  1.0  0.0  0.0           81        75
13      1     0  0.0  1.0  0.0           71        91

In [146]:
from sklearn.model_selection import train_test_split

In [147]:
x_train, x_test, y_train, y_test = train_test_split(lastDatas.iloc[:,:-1], lastDatas.iloc[:,-1:], test_size=0.33, random_state=0)

In [148]:
from sklearn.linear_model import LinearRegression

In [149]:
regressor = LinearRegression()

In [150]:
regressor.fit(x_train, y_train)

LinearRegression()

In [151]:
y_pred = regressor.predict(x_test)
y_pred

array([[84.45365573],
       [63.93839954],
       [85.76050662],
       [64.21013241],
       [75.06793322]])

In [152]:
import statsmodels.api as sm

In [153]:
X = np.append(arr=np.ones((14,1)).astype(int), values=lastDatas.iloc[:,:-1], axis=1)

In [154]:
X_l = lastDatas.iloc[:,[0,1,2,3,4,5]].values

In [155]:
X_l = np.array(X_l, dtype=float)

In [156]:
model = sm.OLS(lastDatas.iloc[:,-1:], X_l).fit()

In [157]:
import warnings
warnings.filterwarnings('ignore')

In [158]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:               humidity   R-squared:                       0.294
Model:                            OLS   Adj. R-squared:                 -0.148
Method:                 Least Squares   F-statistic:                    0.6653
Date:                Wed, 07 Dec 2022   Prob (F-statistic):              0.661
Time:                        15:00:07   Log-Likelihood:                -49.542
No. Observations:                  14   AIC:                             111.1
Df Residuals:                       8   BIC:                             114.9
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -4.0286      7.229     -0.557      0.593     -20.698      12.641
x2            -8.2778      8.029     -1.031      0.333     -26.793      10.237
x3            52.3891     50.214      1.043      0.327     -63.404     168.183
x4            55.6337     45.233      1.230      0.254     -48.673     159.940
x5            49.4291     48.337      1.023      0.336     -62.035     160.893
x6             0.4920      0.597      0.825      0.433      -0.884       1.868
==============================================================================
Omnibus:                        0.935   Durbin-Watson:                   2.416
Prob(Omnibus):                  0.627   Jarque-Bera (JB):                0.823
Skew:                           0.389   Prob(JB):                        0.663
Kurtosis:                       2.103   Cond. No.                     2.08e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.08e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [159]:
lastDatas = lastDatas.iloc[:,1:]

In [160]:
X = np.append(arr=np.ones((14,1)).astype(int), values=lastDatas.iloc[:,:-1], axis=1)

In [161]:
X_l = lastDatas.iloc[:,[0,1,2,3,4]].values

In [162]:
X_l = np.array(X_l, dtype=float)

In [163]:
model = sm.OLS(lastDatas.iloc[:,-1 :], X_l).fit()

In [164]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:               humidity   R-squared:                       0.266
Model:                            OLS   Adj. R-squared:                 -0.060
Method:                 Least Squares   F-statistic:                    0.8165
Date:                Wed, 07 Dec 2022   Prob (F-statistic):              0.546
Time:                        15:00:07   Log-Likelihood:                -49.809
No. Observations:                  14   AIC:                             109.6
Df Residuals:                       9   BIC:                             112.8
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -6.2865      6.909     -0.910      0.387     -21.916       9.343
x2            36.6564     39.905      0.919      0.382     -53.615     126.927
x3            41.9135     36.464      1.149      0.280     -40.573     124.400
x4            35.1064     39.339      0.892      0.395     -53.884     124.097
x5             0.6484      0.506      1.282      0.232      -0.496       1.793
==============================================================================
Omnibus:                        0.887   Durbin-Watson:                   2.360
Prob(Omnibus):                  0.642   Jarque-Bera (JB):                0.810
Skew:                           0.424   Prob(JB):                        0.667
Kurtosis:                       2.181   Cond. No.                     1.73e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.73e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [165]:
x_train = x_train.iloc[:,1:]

In [166]:
x_test = x_test.iloc[:,1:]

In [168]:
regressor.fit(x_train, y_train)

LinearRegression()

In [170]:
y_pred = regressor.predict(x_test)
y_pred

array([[77.98135142],
       [68.29304916],
       [81.05037539],
       [71.44926132],
       [75.78905304]])